on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: checkout
      uses: actions/checkoutv2
    - name: Hello world action step
      id: hello
      uses: ./
      with:
        who-to-greet: 'Alex Parra'
    - name: Get the output time
      run: echo "The time was  ${{ steps.hello.output.time }}"
